package com.telusko.quizapp.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Data
@Entity
public class Question {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String questionTitle;
    private String optiona1;
    private String optiona2;
    private String optiona3;
    private String optiona4;
    private String rightAnswer;
    private String difficultyLevel;
    private String category;
    // Getters and setters (automatically generated by Lombok's @Data)
}
